name: Stock Data Ingestion
on:
    workflow_dispatch:
    schedule:
        - cron: '0 11 * * 1-5'

jobs:
    ingest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.14'

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run ingestion script
              run: |
                  python pull.py
            - name: Upload data as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: stock-data
                  path: data/